// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rhztqshwbyfcfnvhjjzc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJoenRxc2h3YnlmY2ZudmhqanpjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQwMTExMTEsImV4cCI6MjA2OTU4NzExMX0.dotdnJ46T6oye-rNOQW1ODNYTfQoZEpq7DAnQn2o7rQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});